### ISSUE TITLE
about the CDF of the kernel vinecopula 

### ISSUE THREAD

**Issue by Taalmasoud** [tnagler/kdevine#12]
Dear Nagler

I need help in R, please.
usually, any package of any distribution in R contains three commands such as rname, dname and pname. I found a package called kdevine  https://github.com/tnagler/kdevine 

and it has dkdevinecop and rkdevinecop but it doesn't have the option pkdevinecop (the CDF). I tried to write it like this but it is wrong, could you see it, please

Regards

library(kdevine)
library(kdecopula)

data(wdbc)

fit <- kdevine(wdbc[, 5:7], xmin = rep(0, 3))
f<-dkdevine(wdbc[, 5:7], fit)

for(i in 1:length(f)){
p<-sum(dkdevinecop(c(wdbc[, 5],wdbc[,6],wdbc[,7]),fit))
}
print (p)

**Comment by tnagler** [comment]
- You are correct that this package does not have an option for the CDF. The CDF of vine copula models is not generally available in closed form, so numerical techniques are required to evaluate it. 

- I'm not sure what your code is supposed to do, but it is certainly not calculating a CDF.

- The easiest way is probably Monte Carlo simulation via `rkdevine()`. Then you only need to compute proportions of simulated data falling into the box of interest. For example, `mean(rkdevine(1000, fit) <= c(0.2, 0.5, 0.4))`.

- The rvinecopulib library does provide such functionality automatically. Choosing `family_set = "tll"` during fitting fits kernel copulas. See then documentation of this library.

**Comment by Taalmasoud** [comment]
Dear Tnagler

Thank you. Is there a function(CDF) for the kernel copula in the multivariate case? 

Regards

**Comment by tnagler** [comment]
Not in this package.

**Comment by Taalmasoud** [comment]
where I could find it, please? 
I just found the bivariate case(kdecop)

Regards

**Comment by tnagler** [comment]
https://vinecopulib.github.io/rvinecopulib/reference/vinecop.html 
https://vinecopulib.github.io/rvinecopulib/reference/vinecop_methods.html
For kernel copulas, use `family_set = "all"` as mentioned above.

**Comment by Taalmasoud** [comment]
Thank you so much.
