### ISSUE TITLE
categorical variables

### ISSUE THREAD

**Issue by synikitin** [tnagler/kdevine#4]
Hey again :) One issue I am running into is handling categorical variables in a principled manner - I jittered mine to get an approximate answer. 

Are there any theoretical obstacles with adding something like Aitchison-Aitken kernel and the corresponding CDF to also handle unordered, categorical data, similar to [np](https://github.com/djachoc/R-Package-npRmpi) package, while still maintaining control of the curse of dimensionality?

**Comment by tnagler** [comment]
Indeed, there is a theoretical obstacle. If a random variable _X_ is discrete, the probability integral transform _U = F_X(X)_ is no longer a uniform random variable and, thus, cannot be model by a copula. I am halfway through a paper on how to deal with such issues. It will take a while until it's implemented in this package, but I can give you more information via mail.
